/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gfa.ejerciciopracticogfa;

/**
 *
 * @author Hecto
 */
public class Sesiones extends javax.swing.JFrame {

    /**
     * Creates new form Sesiones
     */
    public Sesiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jPSuperior = new javax.swing.JPanel();
        jBVolver = new javax.swing.JButton();
        jLSes1 = new javax.swing.JLabel();
        jPInferior = new javax.swing.JPanel();
        jSPUltimasSes = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setLayout(new java.awt.BorderLayout());

        jPSuperior.setLayout(new java.awt.BorderLayout());

        jBVolver.setText("VOLVER");
        jPSuperior.add(jBVolver, java.awt.BorderLayout.WEST);

        jLSes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSes1.setText("ULTIMAS SESIONES");
        jPSuperior.add(jLSes1, java.awt.BorderLayout.CENTER);

        Fondo.add(jPSuperior, java.awt.BorderLayout.PAGE_START);

        jPInferior.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSPUltimasSes.setViewportView(jTable1);

        jPInferior.add(jSPUltimasSes, java.awt.BorderLayout.CENTER);

        Fondo.add(jPInferior, java.awt.BorderLayout.CENTER);

        getContentPane().add(Fondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sesiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLSes1;
    private javax.swing.JPanel jPInferior;
    private javax.swing.JPanel jPSuperior;
    private javax.swing.JScrollPane jSPUltimasSes;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
